[package]
name = "racksonracks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rutie = "0.8.4"

[lib]
name = "racksonracks"
crate-type = ["cdylib"]
